#!/bin/bash
#BATCH --job-name=seg
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla-smx2:1

source /scratch/itee/uqasha24/miniconda3/bin/activate /scratch/itee/uqasha24/miniconda3/envs/robust_dl
python3 /scratch/itee/uqasha24/synthetic-generalisation/method:synthseg/SegMRI/inference.py -d /scratch/itee/uqasha24/synthetic-generalisation/10010_only_data/ -p ./tempout/ --model segmenter --data organ --nepochs 69 --datatype organ --datasetName organ --modelDir ./10010_only/
